### ISSUE TITLE
Specify Solidity pragma in code snippets

### ISSUE THREAD

**Issue by paulrberg** [kadenzipfel/gas-optimizations#1]
Love this repository, but I think that there's an important piece of data missing from the code snippets: a Solidity pragma.

Gas costs differ between Solidity compiler versions, and in some cases the code may not even compile.

**Comment by pcaversaccio** [comment]
Good point - actually wanted to open a similar issue. Some of the issues are mitigated by the latest Solidity versions (using the optimiser ofc).
